name: Daily Motivation Update

on:
  schedule:
    
    - cron: '0 0 * * *'
  workflow_dispatch: 

jobs:
  update-quote:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python update_quote.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add README.md
          git commit -m "Updated daily motivation quote" || exit 0
          git push
